### ISSUE TITLE
Convert password hashing into a smarter trait

### ISSUE THREAD

**Issue by benallfree** [adonisjs/adonis-api-app#8]
Related to https://github.com/adonisjs/adonis-lucid/issues/198

This one kind of bit me, I was doing a big data import and didn't realize it was `bcrypt`ing every model instance.

I'd like to do something like this:

```javascript
User.unguardPasswords()
...bulk import...
User.guardPasswords()
```

(In order to do this, Lucid needs a good way of allowing traits to add properties to the `__setters__` array.)

**Comment by benallfree** [comment]
Full code example. I feel this is cleaner than using hooks, and it allows for password hash bypassing in cases of bulk imports with already hashed passwords.

```javascript
class Autohash {
  register (Model) {
    let isPasswordPrehashed = false;
    Model.unguardPasswords = function()
    {
      isPasswordPrehashed = true;
    }
    Model.guardPasswords = function()
    {
      isPasswordPrehashed = false;
    }
    Model.addHook('beforeCreate', async (userInstance) => {
      if (userInstance.password && !isPasswordPrehashed) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
  }
}

class User extends Model {
  static boot () {
    super.boot()
    this.addTrait('App/Models/Traits/Autohash')
  }
}
```

**Comment by thetutlage** [comment]
I believe you are trying to set properties on the `Model` class, since it should be done on `model instances`. Why?

The `User` model will not be used at a single place, so setting a global flag will mess up bunch of things. 

For example: You have 2 HTTP routes, in one route you want to `guardPasswords` and in 2nd one you want to `unguardPasswords`.

Now if both requests will hit the server at the same time, you have no idea what will happen, since both requests are using the same `Model` and toggling flags together.

The elegant solution is set these properties on the instance of each `user`.

## Triat

```js
class Autohash {
  _addSetters (modelInstance) {
    if (modelInstance.__setters__.indexOf('isPasswordPrehashed') === -1) {
      modelInstance.__setters__.push('isPasswordPrehashed')
    }
  }

  register (Model) {
    const self = this

    Model.prototype.unguardPasswords = function () {
      self._addSetters(this)
      this.isPasswordPrehashed = true
      return this
    }

    Model.prototype.guardPasswords = function () {
      self._addSetters(this)
      this.isPasswordPrehashed = false
      return this
    }

    Model.addHook('beforeCreate', async (userInstance) => {
      if (userInstance.password && !userInstance.isPasswordPrehashed) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
  }
}
```

The `_addSetters` method hack can be removed, if Lucid provides an elegant way for that.

## Usage

```js
const user = new User()
user.username = 'virk'
user.age = 22

await user.unguardPasswords().save()
```

## Note
Knowing the fact you have PHP background.

Node is different from Php, since it handles request asynchronously and same memory is shared between all the requests.

Whereas in Php, each request is a thread of it's own and has isolated memory.

**Comment by benallfree** [comment]
You're right, I didn't even think about shared memory! Thank you, I just learned a lot from how you solved this one.

How would this work with `User.create()`?

**Comment by thetutlage** [comment]
I don't think this will work with `User.create`, since that simply hides the user instance unless it's persisted to the db.

What one can do is

```js
const user = new User()
user.fill(DATA_OBJECT)

await user.unguardPasswords().save()
```

So docs needs to have a note about this when using your trait

**Comment by benallfree** [comment]
I kind of like this solution to avoid polluting `__setters__` and to have some kind of per-instance local state for each trait. It would require Lucid to generate some kind of unique signature for each trait registered on a model.

```javascript
class Autohash {
  register (Model, traitSig) {
    Model.prototype.unguardPasswords = function () {
      this.traitsBag(traitSig).isPasswordPrehashed = true
      return this
    }

    Model.prototype.guardPasswords = function () {
      this.traitsBag(traitSig).isPasswordPrehashed = false
      return this
    }

    Model.addHook('beforeCreate', async (userInstance) => {
      if (userInstance.password && !userInstance.traitsBag(traitSig).isPasswordPrehashed) {
        userInstance.password = await Hash.make(userInstance.password)
      }
    })
    
    // Return defaults for initializing traitsBag entry
    return {
      isPasswordPrehashed: true
    }
  }
}
```

**Comment by thetutlage** [comment]
Closing since not actionable
